export const CONSTANTS = {
  NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID:
    process.env.NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID,
  NEXT_PUBLIC_HIGHLIGHT_BACKEND_URL:
    process.env.NEXT_PUBLIC_HIGHLIGHT_BACKEND_URL,
};
